name: Update Coverage Badge

on:
  push:

jobs:
  update-coverage-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install project
        run: poetry install --no-interaction

      - name: Run Coverage
        run: |
          source .venv/bin/activate
          poetry run coverage run -m unittest discover tests -p "tests_functions.py"
          poetry run coverage report
          
      - name: Coverage Badge
        uses: tj-actions/coverage-badge-py@v2

      - name: Update README
        run: |
          sed -i 's|<!-- COVERAGE BADGE -->|![Coverage Badge](coverage-badge.svg)|' README.md
        if: steps.verify-changed-files.outputs.files_changed == 'true'

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md coverage-badge.svg
          git commit -m "Update coverage badge"
          git push
        if: steps.verify-changed-files.outputs.files_changed == 'true'
